"""
Feed de notícias macro (RSS + Binance + DeepSeek) → Supabase `macro_feed`.

Executar em paralelo no VPS:
  python3 macro_radar.py

Cria a tabela no Supabase (SQL) se ainda não existir:

  create table if not exists public.macro_feed (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    bullet_points jsonb not null,
    macro_score int not null check (macro_score >= 0 and macro_score <= 100),
    market_vibe text not null
  );

  create table if not exists public.system_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    source text not null,
    message text not null,
    level text not null default 'info'
  );
"""

from __future__ import annotations

import json
import os
import re
import time
import urllib.request
from datetime import datetime, timezone
from typing import Any

import feedparser
from dotenv import load_dotenv
from openai import OpenAI
from supabase import create_client

RSS_URL = "https://cointelegraph.com/rss"
BINANCE_TICKER = "https://api.binance.com/api/v3/ticker/price?symbol={symbol}"
SLEEP_S = 1800
MAX_HEADLINES = 5

SYSTEM_PROMPT = (
    "Atuas como um analista macroeconómico. Lê estas manchetes e preços. "
    "Resume o sentimento do mercado em 3 bullet points curtos e define o Macro Score "
    "de 0 (Bear extremo) a 100 (Bull extremo). Responda APENAS em JSON com as chaves: "
    '"bullet_points" (lista), "macro_score" (int) e "market_vibe" (string curta).'
)


def _supabase():
    url = (os.getenv("SUPABASE_URL") or "").strip()
    key = (os.getenv("SUPABASE_KEY") or "").strip()
    if not url or not key:
        return None
    return create_client(url, key)


def log_to_supabase(source: str, message: str, level: str = "info") -> None:
    sb = _supabase()
    if sb is None:
        return
    try:
        sb.table("system_logs").insert(
            {"source": source, "message": message, "level": level}
        ).execute()
    except Exception as e:  # noqa: BLE001
        print(f"⚠️ log_to_supabase falhou: {e}")


def _http_json(url: str, timeout: int = 20) -> dict[str, Any]:
    req = urllib.request.Request(url, headers={"User-Agent": "AuricMacroRadar/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode())


def fetch_binance_spot(symbol: str) -> float:
    data = _http_json(BINANCE_TICKER.format(symbol=symbol))
    return float(data["price"])


def fetch_rss_headlines(url: str, limit: int) -> list[str]:
    parsed = feedparser.parse(url)
    out: list[str] = []
    for entry in getattr(parsed, "entries", []) or []:
        title = (getattr(entry, "title", None) or "").strip()
        if title:
            out.append(title)
        if len(out) >= limit:
            break
    return out


def _extract_json_object(raw_text: str) -> dict[str, Any]:
    txt = str(raw_text or "").strip()
    if not txt:
        raise ValueError("Resposta vazia.")
    try:
        obj = json.loads(txt)
        if isinstance(obj, dict):
            return obj
    except json.JSONDecodeError:
        pass
    m = re.search(r"\{[\s\S]*\}", txt)
    if not m:
        raise ValueError("JSON não encontrado na resposta.")
    obj = json.loads(m.group(0))
    if not isinstance(obj, dict):
        raise ValueError("JSON retornado não é objeto.")
    return obj


def analyze_with_deepseek(headlines: list[str], btc: float, eth: float) -> dict[str, Any]:
    api_key = (os.getenv("DEEPSEEK_API_KEY") or "").strip()
    if not api_key:
        raise RuntimeError("DEEPSEEK_API_KEY não configurada.")
    client = OpenAI(api_key=api_key, base_url="https://api.deepseek.com")
    user_blob = {
        "headlines": headlines,
        "btc_usdt": btc,
        "eth_usdt": eth,
    }
    response = client.with_options(timeout=60.0).chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(user_blob, ensure_ascii=False)},
        ],
        max_tokens=500,
        temperature=0.2,
    )
    content = (response.choices[0].message.content or "").strip()
    parsed = _extract_json_object(content)
    bullets = parsed.get("bullet_points")
    if not isinstance(bullets, list):
        bullets = [str(bullets)] if bullets is not None else []
    bullets = [str(b).strip() for b in bullets if str(b).strip()]
    score_raw = parsed.get("macro_score", 0)
    try:
        macro_score = int(score_raw)
    except (TypeError, ValueError):
        macro_score = 0
    macro_score = max(0, min(100, macro_score))
    vibe = str(parsed.get("market_vibe") or "").strip() or "neutro"
    return {"bullet_points": bullets, "macro_score": macro_score, "market_vibe": vibe}


def insert_macro_feed(sb: Any, row: dict[str, Any]) -> None:
    payload = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "bullet_points": row["bullet_points"],
        "macro_score": row["macro_score"],
        "market_vibe": row["market_vibe"],
    }
    sb.table("macro_feed").insert(payload).execute()


def run_cycle() -> None:
    sb = _supabase()
    if sb is None:
        raise RuntimeError("SUPABASE_URL / SUPABASE_KEY em falta.")

    headlines = fetch_rss_headlines(RSS_URL, MAX_HEADLINES)
    if not headlines:
        raise RuntimeError("RSS sem entradas (verifica URL ou rede).")

    log_to_supabase(
        "RADAR",
        f"RSS: {len(headlines)} manchetes; destaque: {headlines[0][:200]}",
        "info",
    )

    btc = fetch_binance_spot("BTCUSDT")
    eth = fetch_binance_spot("ETHUSDT")

    result = analyze_with_deepseek(headlines, btc, eth)
    insert_macro_feed(sb, result)
    print(
        f"[macro_radar] OK macro_score={result['macro_score']} "
        f"vibe={result['market_vibe']!r} bullets={len(result['bullet_points'])}"
    )
    log_to_supabase(
        "RADAR",
        f"macro_feed gravado: score={result['macro_score']} vibe={result['market_vibe']!r}",
        "info",
    )


def main() -> None:
    load_dotenv()
    print("[macro_radar] Arranque — ciclo a cada 30 min (Ctrl+C para parar).")
    log_to_supabase("RADAR", "macro_radar arranque — ciclo a cada 30 min.", "info")
    while True:
        try:
            run_cycle()
        except Exception as e:  # noqa: BLE001
            print(f"[REDE] Conexão perdida: {e}. Tentando reconectar em 5 segundos...")
            log_to_supabase("RADAR", f"Ciclo falhou (retry em 5s): {e}", "warning")
            time.sleep(5)
            continue
        time.sleep(SLEEP_S)


if __name__ == "__main__":
    main()
