-- Execute no SQL Editor do Supabase (ou como migration).

create table if not exists public.decisions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  symbol text not null,
  action text not null check (action in ('BUY', 'SELL', 'HOLD')),
  confidence real,
  raw_response text,
  market_snapshot jsonb not null default '{}'::jsonb,
  model text,
  replicate_prediction_id text
);

create index if not exists idx_decisions_created_at on public.decisions (created_at desc);

create table if not exists public.trades (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  decision_id uuid references public.decisions (id) on delete set null,
  symbol text not null,
  side text not null check (side in ('buy', 'sell')),
  amount numeric not null,
  price numeric,
  order_id text,
  status text not null default 'submitted',
  raw_exchange jsonb default '{}'::jsonb,
  mode text not null default 'paper'
);

create index if not exists idx_trades_created_at on public.trades (created_at desc);

alter table public.decisions enable row level security;
alter table public.trades enable row level security;

-- Ajuste policies conforme sua auth; com service_role no backend RLS pode ser bypassed.
-- Para uso apenas server-side com service_role, as políticas abaixo permitem tudo ao role service.

-- =====================================================================
-- AURIC (estado atual do código) — colunas esperadas em produção
-- =====================================================================
-- Este bloco mantém o schema.sql alinhado ao backend/frontend atuais.
-- As migrações canônicas estão em `supabase/migrations/`.

-- wallet_status (dashboard + sync do ciclo)
create table if not exists public.wallet_status (
  id smallint primary key default 1 check (id = 1),
  usdt_balance double precision not null default 0,
  usdc_balance double precision not null default 0,
  entry_price double precision,
  posicao_aberta boolean not null default false,
  whale_flow_score double precision,
  social_sentiment_score double precision,
  news_sentiment_score integer,
  forecast_preco_alvo double precision,
  forecast_tendencia_alta boolean,
  llava_veto boolean,
  funnel_stage text,
  funnel_abort_reason text,
  ml_prob_base double precision,
  ml_prob_calibrated double precision,
  updated_at timestamptz not null default now()
);

-- logs (telemetria de decisão/execução)
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  par_moeda text not null default 'ETH/USDC',
  preco_atual double precision not null default 0,
  probabilidade_ml double precision not null default 0,
  sentimento_ia text not null default '',
  veredito_ia text,
  acao_tomada text not null default '',
  justificativa text not null default '',
  contexto_raw text,
  justificativa_ia text,
  noticias_agregadas text,
  dist_ema200_pct double precision,
  spread_atual double precision,
  book_imbalance double precision,
  hora_do_dia integer,
  atr_14 double precision,
  funding_rate double precision,
  long_short_ratio double precision,
  whale_flow_score double precision,
  social_sentiment_score double precision,
  funnel_stage text,
  funnel_abort_reason text,
  ml_prob_base double precision,
  ml_prob_calibrated double precision,
  llava_veto boolean,
  commission double precision,
  is_maker boolean,
  rsi_14 double precision,
  adx_14 double precision
);

-- trade_logs (pós-trade / reconciliação)
create table if not exists public.trade_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  par_moeda text,
  symbol text,
  side text,
  amount double precision,
  price double precision,
  order_id text,
  status text,
  decision_id uuid,
  raw_exchange jsonb,
  mode text,
  contexto_raw text,
  qty_left double precision,
  partial_roi double precision,
  final_roi double precision,
  exit_type text,
  whale_flow_score double precision,
  social_sentiment_score double precision,
  alpha_attribution jsonb
);
