-- Auric dashboard — execute no SQL Editor do Supabase (ajuste nomes se já existirem).

-- Tabela de configuração (linha id = 1). O switch SPOT/FUTURES atualiza `trading_mode`.
create table if not exists public.config (
  id integer primary key default 1 check (id = 1),
  trading_mode text not null default 'FUTURES'
    check (trading_mode in ('SPOT', 'FUTURES')),
  modo_operacao text default 'FUTURES'
    check (modo_operacao is null or modo_operacao in ('SPOT', 'FUTURES')),
  balance_usdt numeric,
  pnl_day_pct numeric,
  trades_24h integer,
  xgboost_accuracy numeric,
  ml_probability numeric,
  verdict_ia text,
  justificativa_curta text,
  updated_at timestamptz default now()
);

insert into public.config (id, trading_mode, modo_operacao)
values (1, 'FUTURES', 'FUTURES')
on conflict (id) do nothing;

-- logs: alinhado ao logger Python (registrar_log_trade).
-- `par_moeda`: par negociado (texto). `ativo`: flag booleana na base real — não enviar o símbolo em `ativo`.
-- Se a tabela já existir com schema antigo, migre: add par_moeda, alter ativo para boolean, backfill.
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  par_moeda text not null default 'ETH/USDC',
  ativo boolean not null default true,
  preco_atual double precision not null,
  probabilidade_ml double precision not null default 0,
  sentimento_ia text not null default '',
  veredito_ia text,
  acao_tomada text not null,
  justificativa text not null default '',
  contexto_raw text,
  justificativa_ia text,
  noticias_agregadas text
);

-- Realtime: no painel Supabase, habilite replication para `config`, `logs`,
-- `wallet_status` (saldo USDC) e `bot_control` / `manual_commands` se necessário:
-- alter publication supabase_realtime add table public.config;
-- alter publication supabase_realtime add table public.logs;
-- alter publication supabase_realtime add table public.wallet_status;

-- RLS (desenvolvimento — restrinja em produção com auth).
alter table public.config enable row level security;
alter table public.logs enable row level security;

create policy "config_anon_all"
  on public.config for all
  using (true)
  with check (true);

create policy "logs_anon_select_insert"
  on public.logs for select
  using (true);

create policy "logs_anon_insert"
  on public.logs for insert
  with check (true);

-- wallet_status (estado de posição + mood/funil para dashboard)
create table if not exists public.wallet_status (
  id smallint primary key default 1 check (id = 1),
  usdt_balance double precision,
  usdc_balance double precision,
  entry_price double precision,
  posicao_aberta boolean default false,
  whale_flow_score double precision,
  social_sentiment_score double precision,
  news_sentiment_score integer,
  forecast_preco_alvo double precision,
  forecast_tendencia_alta boolean,
  llava_veto boolean,
  funnel_stage text,
  funnel_abort_reason text,
  ml_prob_base double precision,
  ml_prob_calibrated double precision,
  updated_at timestamptz default now()
);

-- Colunas extras consumidas pelo frontend e geradas pelo backend.
alter table if exists public.logs
  add column if not exists dist_ema200_pct double precision,
  add column if not exists spread_atual double precision,
  add column if not exists book_imbalance double precision,
  add column if not exists hora_do_dia integer,
  add column if not exists atr_14 double precision,
  add column if not exists funding_rate double precision,
  add column if not exists long_short_ratio double precision,
  add column if not exists whale_flow_score double precision,
  add column if not exists social_sentiment_score double precision,
  add column if not exists funnel_stage text,
  add column if not exists funnel_abort_reason text,
  add column if not exists ml_prob_base double precision,
  add column if not exists ml_prob_calibrated double precision,
  add column if not exists llava_veto boolean,
  add column if not exists commission double precision,
  add column if not exists is_maker boolean,
  add column if not exists rsi_14 double precision,
  add column if not exists adx_14 double precision;
