-- Auric dashboard — execute no SQL Editor do Supabase (ajuste nomes se já existirem).

-- Tabela de configuração (linha id = 1). O switch SPOT/FUTURES atualiza `trading_mode`.
create table if not exists public.config (
  id integer primary key default 1 check (id = 1),
  trading_mode text not null default 'FUTURES'
    check (trading_mode in ('SPOT', 'FUTURES')),
  modo_operacao text default 'FUTURES'
    check (modo_operacao is null or modo_operacao in ('SPOT', 'FUTURES')),
  balance_usdt numeric,
  pnl_day_pct numeric,
  trades_24h integer,
  xgboost_accuracy numeric,
  ml_probability numeric,
  verdict_ia text,
  justificativa_curta text,
  updated_at timestamptz default now()
);

insert into public.config (id, trading_mode, modo_operacao)
values (1, 'FUTURES', 'FUTURES')
on conflict (id) do nothing;

-- logs: alinhado ao logger Python (registrar_log_trade).
-- `par_moeda`: par negociado (texto). `ativo`: flag booleana na base real — não enviar o símbolo em `ativo`.
-- Se a tabela já existir com schema antigo, migre: add par_moeda, alter ativo para boolean, backfill.
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  par_moeda text not null default 'ETH/USDT',
  ativo boolean not null default true,
  preco_atual double precision not null,
  probabilidade_ml double precision not null default 0,
  sentimento_ia text not null default '',
  veredito_ia text,
  acao_tomada text not null,
  justificativa text not null default '',
  contexto_raw text,
  justificativa_ia text,
  noticias_agregadas text
);

-- Realtime: no painel Supabase, habilite replication para `config`, `logs`,
-- `wallet_status` (saldo USDT) e `bot_control` / `manual_commands` se necessário:
-- alter publication supabase_realtime add table public.config;
-- alter publication supabase_realtime add table public.logs;
-- alter publication supabase_realtime add table public.wallet_status;

-- RLS (desenvolvimento — restrinja em produção com auth).
alter table public.config enable row level security;
alter table public.logs enable row level security;

create policy "config_anon_all"
  on public.config for all
  using (true)
  with check (true);

create policy "logs_anon_select_insert"
  on public.logs for select
  using (true);

create policy "logs_anon_insert"
  on public.logs for insert
  with check (true);
