-- Auric dashboard — execute no SQL Editor do Supabase (ajuste nomes se já existirem).

-- Tabela de configuração (linha id = 1). O switch SPOT/FUTURES atualiza `trading_mode`.
create table if not exists public.config (
  id integer primary key default 1 check (id = 1),
  trading_mode text not null default 'FUTURES'
    check (trading_mode in ('SPOT', 'FUTURES')),
  modo_operacao text default 'FUTURES'
    check (modo_operacao is null or modo_operacao in ('SPOT', 'FUTURES')),
  balance_usdt numeric,
  pnl_day_pct numeric,
  trades_24h integer,
  xgboost_accuracy numeric,
  ml_probability numeric,
  verdict_ia text,
  justificativa_curta text,
  updated_at timestamptz default now()
);

insert into public.config (id, trading_mode, modo_operacao)
values (1, 'FUTURES', 'FUTURES')
on conflict (id) do nothing;

-- Se a tabela já existir sem a coluna:
-- alter table public.config add column if not exists modo_operacao text
--   default 'FUTURES' check (modo_operacao is null or modo_operacao in ('SPOT', 'FUTURES'));
-- update public.config set modo_operacao = coalesce(modo_operacao, trading_mode) where id = 1;

-- trade_logs: alinhado ao logger Python (registrar_log_trade).
-- Se a tabela já existir, garanta colunas equivalentes + created_at para contagens 24h.
create table if not exists public.trade_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ativo text not null,
  preco_atual double precision not null,
  probabilidade_ml double precision not null default 0,
  sentimento_ia text not null default '',
  acao_tomada text not null,
  justificativa text not null default ''
);

-- Realtime: no painel Supabase, habilite replication para `config` e `trade_logs`,
-- ou execute (ignore erro se as tabelas já estiverem na publicação):
-- alter publication supabase_realtime add table public.config;
-- alter publication supabase_realtime add table public.trade_logs;

-- RLS (desenvolvimento — restrinja em produção com auth).
alter table public.config enable row level security;
alter table public.trade_logs enable row level security;

create policy "config_anon_all"
  on public.config for all
  using (true)
  with check (true);

create policy "trade_logs_anon_select_insert"
  on public.trade_logs for select
  using (true);

create policy "trade_logs_anon_insert"
  on public.trade_logs for insert
  with check (true);
