-- Comandos manuais (dashboard / SQL): o maestro executa em Futuros e marca executed.
create table if not exists public.manual_commands (
  id bigint generated by default as identity primary key,
  command text not null check (command in ('LONG', 'SHORT')),
  executed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

comment on table public.manual_commands is 'Fila LONG/SHORT manual; executed=false até o main.py processar.';

alter table public.manual_commands enable row level security;

create policy "manual_commands_select_anon"
  on public.manual_commands for select
  to anon, authenticated
  using (true);

create policy "manual_commands_insert_anon"
  on public.manual_commands for insert
  to anon, authenticated
  with check (true);

create policy "manual_commands_update_anon"
  on public.manual_commands for update
  to anon, authenticated
  using (true)
  with check (true);
