-- Comandos chave/valor (dashboard): observação de mercado para o Brain (Claude).
create table if not exists public.bot_commands (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text,
  active boolean not null default false,
  updated_at timestamptz not null default now()
);

comment on table public.bot_commands is 'Comandos genéricos; ex.: market_observation → contexto humano no prompt do Brain.';

alter table public.bot_commands enable row level security;

create policy "bot_commands_select_anon"
  on public.bot_commands for select
  to anon, authenticated
  using (true);

create policy "bot_commands_insert_anon"
  on public.bot_commands for insert
  to anon, authenticated
  with check (true);

create policy "bot_commands_update_anon"
  on public.bot_commands for update
  to anon, authenticated
  using (true)
  with check (true);

insert into public.bot_commands (key, value, active)
values ('market_observation', '', false)
on conflict (key) do nothing;
